### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [vrza/node-blake2#18]
Would it be possible to tag the released versions, so that differences between versions becomes easier to see?

According to https://www.npmjs.com/package/blake2, latest release was made about 20 hours ago, which makes me guess it is the commit https://github.com/vrza/node-blake2/commit/8ca33e56db1137c95fd7df9a07a70909d7aae17d, which was merged some 23 hours ago.

This could be tagged: 

```sh
git tag v4.0.0 8ca33e56db1137c95fd7df9a07a70909d7aae17d
```

**Comment by vrza** [comment]
@paazmaya Added tags for releases going back to March 2016. Also added comprehensive release notes for last few releases.
