### ISSUE TITLE
Blake3

### ISSUE THREAD

**Issue by tgrecojs** [vrza/node-blake2#21]
First off, I want to say thanks for creating this library! I'm using it inside of a tutorial I'm writing on hash functions - will be sure to link back! That said.... Is there a plan to implement the new blake3 spec into here? I know it's super new, but this repo is the most up to date of any blake2 JS implementations so I thought I'd reach out.

https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf

Thanks again!

**Comment by vrza** [comment]
Thanks! Interested in reading that tutorial when you finish it.

A stand-alone project would make more sense than adding BLAKE3 support to node-blake2 -- the BLAKE3 reference implementation is also a separate project from the BLAKE2 reference implementation.

The canonical implementation of BLAKE3 seems to be in Rust, and there seems to be a C implementation as well. Need to research options for calling Rust code from Node.js, to see if there's a feasible approach, or going with the C implementation makes more sense.

If anyone is interested in backing a node-blake3 project, please contact me.
