### ISSUE TITLE
blake2 fails on Mac M1 chip Macbook Pro 

### ISSUE THREAD

**Issue by Manik-Jain** [vrza/node-blake2#32]
Hi,

When I'm trying to execute a test code with Blake2 hash functions on my M1 chip apple macbook, it fails with the following error:  

```Error: dlopen(<My local path>/server/node_modules/blake2/build/Release/binding.node, 0x0001): tried: '<My local path>/node_modules/blake2/build/Release/binding.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/binding.node' (no such file), '/usr/lib/binding.node' (no such file)```

Please be advised, I've replaced the URI with `<My local path>` in the above error

**Comment by vrza** [comment]
@Manik-Jain On first glance it seems that `node-blake2` built a native arm64 binary for your M1 chip (`binding.node`), but you are actually running an x86_64 node.js binary (through [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2)). Please run

```
file "$(which node)"
```

in your shell and paste the output here.

**Comment by vrza** [comment]
This seems like a mistake on the user's side, and since they did not reply in over a month, I feel that it's safe to close this ticket.

**Comment by punithbm** [comment]
@vrza  I am also going through same issue this is the out put for that command 
```.nvm/versions/node/v16.19.0/bin/node: Mach-O 64-bit executable x86_64```

**Comment by vrza** [comment]
@punithbm As explained above, you're running a pure x86_64 build of Node.js on an Apple silicon CPU. The solution is to use a native Apple silicon (arm64) version of node.

**Comment by punithbm** [comment]
@vrza  it got resolved after re installing xcode and nvm.
